name: Deploy GS Data

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: "0 */12 * * *"   # 每12小时运行一次，你也可以改成每天

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout google-scholar-stats branch
        uses: actions/checkout@v4
        with:
          ref: google-scholar-stats
          path: scholar

      - name: Copy gs_data.json to main branch
        run: |
          cp scholar/gs_data.json ./gs_data.json

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add gs_data.json
          git commit -m "Update gs_data.json" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-gs-data
          commit-message: "Update gs_data.json"
          title: "Update gs_data.json"
          body: "Automated update of Google Scholar data"
          base: main
          delete-branch: true
          labels: |
            automated pr
          draft: false

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
