name: Deploy GS Data

on:
  workflow_run:
    workflows: ["Get Citation Data"]  # 必须和google_scholar_crawler.yaml里的name一致
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout google-scholar-stats branch
        uses: actions/checkout@v3
        with:
          ref: google-scholar-stats
          path: gs

      - name: Copy gs_data.json to main branch
        run: |
          mkdir -p _data
          cp gs/gs_data.json ./_data/gs_data.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-gs-data
          git add _data/gs_data.json
          git commit -m "Update gs_data.json from google-scholar-stats" || echo "No changes to commit"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-gs-data
          title: "Update gs_data.json"
          body: "Automated update of gs_data.json from google-scholar-stats"
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
