name: Deploy GS Data

on:
  workflow_run:
    workflows: ["Get Citation Data"]  # 必须和google_scholar_crawler.yaml里的name一致
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout google-scholar-stats branch
        uses: actions/checkout@v3
        with:
          ref: google-scholar-stats
          path: gs

      - name: Copy gs_data.json to main branch
        run: |
          mkdir -p _data
          cp gs/gs_data.json ./_data/gs_data.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-gs-data
          git add _data/gs_data.json
          git commit -m "Update gs_data.json from google-scholar-stats" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-gs-data
          commit-message: "Update gs_data.json"
          title: "Update gs_data.json"
          body: "Automated update of Google Scholar data"
          base: main
          delete-branch: true
          labels: |
            automated pr
          draft: false

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
