name: Deploy GS Data

on:
  workflow_run:
    workflows: ["Get Citation Data"]  # 必须和google_scholar_crawler.yaml里的name一致
    types:
      - completed

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Checkout google-scholar-stats branch
        uses: actions/checkout@v3
        with:
          ref: google-scholar-stats
          path: gs

      - name: Copy gs_data.json to main branch
        run: |
          mkdir -p _data
          cp gs/gs_data.json ./_data/gs_data.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/gs_data.json
          if git commit -m "Update gs_data.json from google-scholar-stats"; then
            git push origin main
          else
            echo "No changes to commit"
          fi
